### ISSUE TITLE
Texterify and Stringify TMS got removed

### ISSUE THREAD

**Issue by chrztoph** [jpomykala/awesome-i18n#13]
Hello,

in the following [commit](https://github.com/jpomykala/awesome-i18n/commit/b4105bdcd25505cd28f0f27afa8f9d5cceefd8da#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L150) the TMS

- Texterify
- Stringify

got removed. I think this was a mistake as the commit message only says "Sorting"?

Thank you!

**Comment by jpomykala** [comment]
Thanks for noticing! Could you and them again? :)

**Comment by jpomykala** [comment]
Hey @PharmaShop thanks for your work on sorting and cleaning the content. Is there any reason why these to got removed?

**Comment by chrztoph** [comment]
Sure: https://github.com/jpomykala/awesome-i18n/pull/14

**Comment by jpomykala** [comment]
Great and thanks again! Most of approvals I’m doing on my phone, so I’m not always very picky in reviews :)
